version: 2
orbs: 
  maven: circleci/maven@1.2.0
jobs:
  build-test:
    docker: 
      - image: cimg/openjdk:16.0.2-node
    steps:
      - checkout
      - run:
          name: Build and verifiy
          command: mvn clean verify
      - run:
          name: Package application
          command: mvn package
      - run:
          name: Clean up generated results
          command: |
            rm -rf target/classes
            rm -rf target/failsafe-reports
            rm -rf target/generated-sources 
            rm -rf target/generated-test-sources
            rm -rf target/maven-archiver
            rm -rf target/maven-status
            rm target/surefire-reports/*.dumpstream
            rm -rf target/test-classes
      - run:
          name: Zip test coverage
          command: zip -r coverage.zip target/site/jacoco-ut
      - store-artifacts:
          path: coverage.zip
          name: coverage.zip
      - store-test-results:
          path: target/surefire-reports
      - store-artifacts:
          path: target/spring-practice-0.0.1.jar
  
  compose:
    machine: true
    steps:
      - checkout
      - run:
          name: build containerized application
          command: docker compose build
      
workflows:
  version: 2
  build:
    jobs:
      - build-test
      - compose