version: 2
orbs:
  maven: circleci/maven@1.2.0

jobs:
  build-test:
    docker:
      - image: cimg/openjdk:16.0.2-node
    steps:
      - checkout
      - run:
          name: Build and verifiy
          command: mvn clean verify
      - run:
          name: Package application
          command: mvn package
      - run:
          name: Clean up generated results
          command: |
            rm -rf target/classes
            rm -rf target/failsafe-reports
            rm -rf target/generated-sources 
            rm -rf target/generated-test-sources
            rm -rf target/maven-archiver
            rm -rf target/maven-status
            rm target/surefire-reports/*.dumpstream
            rm -rf target/test-classes
      # - run:
      #     name: Zip test coverage
      #     command: zip -r coverage.zip target/site/jacoco-ut
      # - store-artifacts:
      #     path: coverage.zip
      #     name: coverage.zip
      - store-artifacts:
          path: target/site/jacoco-ut
      - store-test-results:
          path: target/surefire-reports
      - store-artifacts:
          path: target/spring-practice-0.0.1.jar
          name: app.jar
      - run:
          name: Upload coverage statistics to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  compose:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Containerized Application
          command: docker-compose build

  automation:
    machine: true
    steps:
      - checkout
      - run:
          name: Create Database Storage
          command: mkdir ~/mysql-data
      - run:
          name: Start Test MySQL DB
          command: docker run -d \
            --name spring-test-db \
            -p 3306:3306 \
            -v mysql-data:/var/lib/mysql \
            -e MYSQL_ROOT_PASSWORD='123456' \
            -e MYSQL_USER='springuser' \
            -e MYSQL_PASSWORD='ThePassword' \
            -e MYSQL_DATABASE='SPRING' \
            mysql
      - run:
          name: Create Environment Config
          command: echo "SECRET_KEY=$(openssl rand -base64 64)" > .env
      - run:
          name: Run API Tests
          command: |
            mvn clean install -DskipTests
            mvn failsafe:integration-test
      - store-test-results:
          path: target/failsafe-reports
          # Skip codecov upload for now until I figure out how to get both the failsafe and surefire results working

workflows:
  version: 2
  build:
    jobs:
      - build-test
      - compose
      - automation:
          requires:
            - build-test
            - compose
